name: miniquest_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase 関連のパッケージ
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1


  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  image_picker: ^1.2.0
  firebase_storage: ^12.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true