// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnk9q2lzrllRUq8Jop_iX6nP_z17TYzqw',
    appId: '1:85339778015:web:24e12db404656eb8def26a',
    messagingSenderId: '85339778015',
    projectId: 'mini-quest-7d63b',
    authDomain: 'mini-quest-7d63b.firebaseapp.com',
    storageBucket: 'mini-quest-7d63b.firebasestorage.app',
    measurementId: 'G-29RXRCJVQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpED7dGgkopkmc4Z6wnjX3RLn-Q29Lffo',
    appId: '1:85339778015:android:df08a8339582914edef26a',
    messagingSenderId: '85339778015',
    projectId: 'mini-quest-7d63b',
    storageBucket: 'mini-quest-7d63b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-HRBxY2cE2kseb9feSloRGnHlp_9NOvo',
    appId: '1:85339778015:ios:958afae3229c9c22def26a',
    messagingSenderId: '85339778015',
    projectId: 'mini-quest-7d63b',
    storageBucket: 'mini-quest-7d63b.firebasestorage.app',
    androidClientId: '85339778015-05nu3rjch7g3vikjkiea5c970p0t44f9.apps.googleusercontent.com',
    iosClientId: '85339778015-mdbbse8lck19lkfkr2et1mu6tr3iai3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniquestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-HRBxY2cE2kseb9feSloRGnHlp_9NOvo',
    appId: '1:85339778015:ios:958afae3229c9c22def26a',
    messagingSenderId: '85339778015',
    projectId: 'mini-quest-7d63b',
    storageBucket: 'mini-quest-7d63b.firebasestorage.app',
    androidClientId: '85339778015-05nu3rjch7g3vikjkiea5c970p0t44f9.apps.googleusercontent.com',
    iosClientId: '85339778015-mdbbse8lck19lkfkr2et1mu6tr3iai3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniquestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnk9q2lzrllRUq8Jop_iX6nP_z17TYzqw',
    appId: '1:85339778015:web:f85a9841e37a256ddef26a',
    messagingSenderId: '85339778015',
    projectId: 'mini-quest-7d63b',
    authDomain: 'mini-quest-7d63b.firebaseapp.com',
    storageBucket: 'mini-quest-7d63b.firebasestorage.app',
    measurementId: 'G-QV13L8NYQJ',
  );
}
